name: school_role
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.1
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_gen: any
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
