name: school_role
description: "A Flutter application for taking attendance and managing classes."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dynamic_color: ^1.8.1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_ui_auth: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_gen: any
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^2.0.0
  cloud_firestore: ^6.0.0
  material_color_utilities: ^0.11.1
  flutter_draggable_gridview: ^0.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
